name: myapp
description: A exported flutter project from FUNCTION12


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
    
  flutter_native_splash: ^2.3.2
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  intl: ^0.19.0
  image_picker: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  http: ^1.2.0
  url_launcher: ^6.1.10
  dio: ^5.1.0
  flutter_cart: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/category/
    - assets/images/homepage/
    - assets/images/shoppage/
    - assets/images/newspage/
    - assets/images/userinfo/
    - assets/images/cart/
    - assets/images/product/

